version: '{APPVEYOR_REPO_TAG_NAME}'
skip_non_tags: true 
image: Visual Studio 2017
environment:
  my_secret:
    secure: oB6h1YHPdFxVwg7++llRwg== # Encriptada em https://ci.appveyor.com/tools/encrypt
  my_salt:
    secure: ip3vQg3F/xDJ2tAs4dINX0ojuK7Z2Qujf3vIUV3fS0CsEpsHtoyrH8gY1KIic8tPCCOHBwaCAFDfRSyvnDvoKA==
branches:
  only:
  - master
configuration: Release
install:
  - cmd: echo %APPVEYOR_REPO_TAG_NAME%
  - cmd: dotnet restore
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  verbosity: minimal
  project: discord-webhook-client.sln
build_script:
  - cmd: dotnet build
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt discord-webhook-client-test\bin\Release\netcoreapp2.2\testSettings.json.enc -secret %my_secret% -salt %my_salt%
  - cmd: dotnet pack
  - cmd: cd discord-webhook-client-test
  - cmd: dotnet test
artifacts:
  - path: '**\discord-webhook-client*.nupkg'
    name: discord-webhook-client-nuget

on_success:
  - echo Processo finalizado com sucesso!
