version: '2.0.{build}'
skip_non_tags: true 
image: Visual Studio 2017
environment:
  my_secret:
    secure: YEDSpsgSp8Q6ER0RbDgAbw== # Encriptada em https://ci.appveyor.com/tools/encrypt
branches:
  only:
  - master
configuration: Release
install:
  - cmd: dotnet restore
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  verbosity: minimal
  project: discord-webhook-client.sln
build_script:
  - cmd: dotnet build
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt discord-webhook-client-test\bin\Release\netcoreapp2.2\testSettings.json.enc -secret %my_secret%
  - cmd: dotnet pack
  - cmd: cd discord-webhook-client-test
  - cmd: dotnet test
artifacts:
  - path: '**\discord-webhook-client*.nupkg'
    name: discord-webhook-client-nuget
#deploy:
  # NuGet
  #- provider: NuGet
  #  api_key:
  #    secure: BbV/KFKLOAbPhQpkPYd4vd84hLJgPvfXGk0OfQ/x4VjHtwjVXla0HVX8LbdOLigX # your encrypted token from Nuget
  #  skip_symbols: false
  #  artifact: discord-webhook-client-nuget
on_success:
  - echo Processo finalizado com sucesso!